### ISSUE TITLE
[Feat]: Add Code_of_Conduct.md

### ISSUE THREAD

**Issue by Annapoornaaradhya** [Tejashri-Taral/TrendTrove-Ecommerce#504] opened 2024-10-17 12:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This Code of Conduct is very important for any opensource project.

### Use Case

It explains all the important guidelines to be followed by the contributors as per the standards of the Open Source Community.

### Benefits

@hars-21 @Tejashri-Taral please assign me this issue under the gssoc-ext and hacktoberfest-accecpted tags 
Thank you

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by harshitpathak528** [comment] 2024-10-22 17:53
If the issue is not solve can you pls assign to me.

**Closed** 2024-10-22 23:43 UTC
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1
